image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .

deploy:
  stage: deploy
  script:
    - echo "Image built successfully. Deploy manually or push to a registry."
  only:
    - main
